server:
  port: 8445
  servlet:
    context-path: /api

spring:
  application:
    name: ai-code-father
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/ai_code?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


# spring doc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zijing.aicode.controller

knife4j:
  enable: true
  setting:
    language: zh_cn


